name: Release

on:
  release:
    types: [published]

jobs:
  build:
    name: Build and release
    runs-on: ubuntu-latest
    env:
      SLUG: keycloak-captchafox
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
      - name: Build
        run: mvn clean compile package
      - name: Upload release asset
        uses: softprops/action-gh-release@v1
        with:
          files: ${{github.workspace}}/target/${{ env.SLUG }}.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
